protocol_class:
  - uniaxial
# The number of list entries in protocol_class and protocol must match 
protocol:
  -
    - 1.0
    - 1.05
    - 2.0
# protocol_init: explicit or linspace
protocol_init: linspace
