kappa_n: 0.0
zeta_n_char: 0.0
w_c_dist: inext_kuhn_grun_fjc
w_c_dfrmtn_dist: log_barrier_clnk_vol_pnlty
b: 1.0
f: 4
p_n_dist: bimodal
p_n_args:
  -
    -
      - 0.1
    -
      - 50
      - 100
  -
    -
      - 0.25
    -
      - 50
      - 100
  -
    -
      - 0.5
    -
      - 50
      - 100
  -
    -
      - 0.75
    -
      - 50
      - 100
  -
    -
      - 0.9
    -
      - 50
      - 100
n:
  -
    - 50
    - 100
n_init: explicit
type_8_chn_clnk: cube