n:
  -
    - 40.
    - 120.
    - 120.
    - 120.
  -
    - 70.
    - 110.
    - 110.
    - 110.
  -
    - 130.
    - 90.
    - 90.
    - 90.
  -
    - 190.
    - 70.
    - 70.
    - 70.
  -
    - 75.
    - 75.
    - 125.
    - 125.
  -
    - 50.
    - 50.
    - 150.
    - 150.
n_init: explicit
w_c_dist: cufjc
w_c_dfrmtn_dist: log_barrier_clnk_vol_pnlty
type_8_chn_clnk: cube
polymer_comp: PDMS
T: 298.