protocol_class:
  - uniaxial
  - uniaxial
# The number of list entries in protocol_class and protocol must match 
protocol:
  -
    - 1.0
    - 2.0
    - 5.0
  -
    - 1.0
    - 0.5
    - 3.0
# protocol_init: explicit or linspace
protocol_init: linspace