protocol_class:
  - uniaxial
  - uniaxial
  - simple_shear
# The number of list entries in protocol_class and protocol must match 
protocol:
  -
    - 1.0
    - 2.0
    - 101.0
  -
    - 1.0
    - 0.5
    - 51.0
  -
    - 0.0
    - 2.0
    - 201.0
# protocol_init: explicit or linspace
protocol_init: linspace